 version: 0.0
 os: linux
 files:
   #unzip
   - source: /
     destination: /home/ec2-user/app
 permissons:
   - object: /home/ec2-user/app
     pattern: "**"
     owner: ec2-user
     group: ec2-user
 hooks:
   AfterInstall:
     - location: set-permissions.sh
   ApplicationStart:
     - location: start-service.sh
        timeout: 300
        runas: ec2-user
   ApplicationStop:
     - location: stop-service.sh
       timeout: 300
       runas: ec2-user


