 version: 0.2

 phases:
    install: 
      runtime-versions: 
         java: corretto11
    pre_build:
      commands:
         - echo Build start on `date`
    build:
      commands:
         - mvn package
         - echo Build completed on `date`

 artifacts:
    files:
     - target/aws-test-fat.jar
     - appspec.yml
     - start-service.sh
     - stop-service.sh
